name: hackapp
description: "A new Flutter project."

publish_to: 'none'

# Versioning info (remove these URLs or comment them)
# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  swipe_cards: ^2.0.0
  material_color_utilities: ^0.11.1  # Add this if needed

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/pics/alice.jpg
    - lib/pics/Bob.jpg
    - lib/pics/Charlie.jpg
    - lib/pics/Diana.jpg
    - lib/pics/Eve.jpg
    - lib/pics/Frank.jpg
    - lib/pics/Grace.jpg
    - lib/pics/Hank.jpg
    - lib/pics/Ivy.jpg
    - lib/pics/Jack.jpg
    - lib/pics/Logo.jpg
    - lib/pics/bac.jpg  # Ensure this matches the actual file name
